### ISSUE TITLE
Use CleanCSS in the loader modal

### ISSUE THREAD

**Issue by AhsanAyaz** [IOMechs/pure-css-loaders#16]
Right now, we use the React bootstrap modal, and the `cssRules` shown are minified.
- Please use the CleanCSS as used [here](https://github.com/IOMechs/pure-css-loaders/blob/main/src/components/Modal/Modal.tsx#L13) to beautify the CSS before showing in the modal
- Delete the `Modal` folder alltogether.

**Comment by mohsinayaz** [comment]
ok
