### ISSUE TITLE
Click to copy the code

### ISSUE THREAD

**Issue by AhsanAyaz** [IOMechs/pure-css-loaders#18]
Right now, in the modal, we have clicked, select and then copy the code.
This ticket is to enable the click to copy feature. 
Floating copy buttons/badges on inside both the HTML and CSS text areas with position absolute, and top, right set to 0 will be implemented

**Comment by mohsinayaz** [comment]
use "https://www.npmjs.com/package/react-copy-to-clipboard" for copy the text

**Comment by AhsanAyaz** [comment]
We'll show an alert on copying the data for now. We'll use the `onCopy` callback from the package.
