### ISSUE TITLE
Landing page with Header only (similar to https://iomechs.github.io/angular-year-calendar/demo/)

### ISSUE THREAD

**Issue by AhsanAyaz** [IOMechs/pure-css-loaders#2]
Landing page with Header only (similar to https://iomechs.github.io/angular-year-calendar/demo/)
This requires a new LandingPage.tsx component, and a Header.tsx component. 
We'll use LandingPage component inside App.tsx and then Header component inside the LandingPage.tsx file

**Comment by Dawood-Shahid** [comment]
Start today: 29 Jul, 3:30pm
Estimate: 01 Aug,

**Comment by AhsanAyaz** [comment]
Closed by #7
