### ISSUE TITLE
Rendering all the loaders on the landing page.

### ISSUE THREAD

**Issue by AhsanAyaz** [IOMechs/pure-css-loaders#3]
Rendering all the loaders on the landing page.
We'll create a folder inside the 'src' folder named 'containers' and inside we'll have Loaders folder. Inside we'll have a Loaders.tsx in which we'll render all the loaders with default sizes.

This includes:
- Hard coded html and css for all the loaders (not using the json files - so keeping it simple)

**Comment by AhmedAli125** [comment]
Estimate: 01 August 2021, 10pm
