### ISSUE TITLE
Clicking on any loader should open a Modal for copying the HTML and CSS of the loader. Similar to what we have on https://loading.io/css/

### ISSUE THREAD

**Issue by AhsanAyaz** [IOMechs/pure-css-loaders#6]
AC:
- Clicking on each loader opens a modal showing the loader's HTML and CSS as strings that can be copied.
- Implement click to copy. This means as soon as the user clicks the HTML or CSS text box, the code is copied to the clipboard. Use the Clipboard Web API for this.

**Comment by AhmedAli125** [comment]
3 Hours

**Comment by Dawood-Shahid** [comment]
start working on it.

**Comment by Dawood-Shahid** [comment]
click to copy not implemented.

**Comment by AhsanAyaz** [comment]
It's more than just the click to copy not implemented.
Let's use React Bootstrap package, and the modal instead of our own for compatibility!

**Comment by Dawood-Shahid** [comment]
Ok, I will try to implement React Bootstrap when I got chance.

**Comment by AhsanAyaz** [comment]
Picking this up

**Comment by AhsanAyaz** [comment]
@Dawood-Shahid , @mohsinayaz please review.
